DATASET:
  TRAIN: "dataset/wholebody34/train.txt"
  VAL: "dataset/wholebody34/val.txt"
  NAMES: "configs/uhd10.names"
MODEL:
  INPUT_WIDTH: 64
  INPUT_HEIGHT: 64
TRAIN:
  LR: 0.00030
  WARMUP: true
  BATCH_SIZE: 64
  END_EPOCH: 300
  OPTIMIZER: adamw
  WEIGHT_DECAY: 0.0001
  SCHEDULER: cosine
  MIN_LR: 0.0
  T_MAX: 300
  CLASSES: 0,7,8,9,10,11,12,13,14,15
RENDER:
  LABEL_IDS: 8,9,10,11,12,13,14,15
  SCORE_IDS:
  PRIORITY_RULES:
    - parent: 7
      children: 8,9,10,11,12,13,14,15
      iou: 0.9
      require_parent_match: true
# TRAIN:
#   LR: 0.0001
#   WARMUP: true
#   BATCH_SIZE: 64
#   END_EPOCH: 300
#   MILESTIONES:
#     - 100
#     - 200
#     - 250
#   CLASSES: 7,8,9,10,11,12,13,14,15
